### ISSUE TITLE
jupyter-lab?

### ISSUE THREAD

**Issue by awgrover** [sumanstats/raku-notebook#1]
Thanks for this docker (and @bduggan for repairing a bug), I got it running. But, I'd like to use the jupyterlab behavior. I tried `-e JUPYTER_ENABLE_LAB=yes` in the `docker run`, but it seems to be plain jupyter.

Am I confused, or is the functionality not there?

**Comment by bduggan** [comment]
Does replacing `/tree` with `/lab` in the url help? e.g. this seems to work: https://hub-binder.mybinder.ovh/user/sumanstats-raku-notebook-jv4m9ytg/lab

**Comment by awgrover** [comment]
Indeed. `/lab` seems to do the trick. Now that I know what to look for, I see that in the [jupyter lab documentation](https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html). Thanks for the speedy response.
